# Simple workflow for deploying static content to GitHub Pages
name: workflow-check

on:
  # Allow this workflow to be called from other workflows
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Type Check
        if: always()
        run: npm run type-check
      - name: Lint
        if: always()
        run: npm run lint
      - name: Formatting Check
        if: always()
        run: npm run format-check
